ibmruntimes/openj9-openjdk-jdk9

closed/get_j9_source.sh
Eclipse OpenJ9's landing page describes a series of commands that
demonstrate how to build OpenJDK with OpenJ9 using a Docker file.
Following those instructions, the get_sources.sh command fails
because get_j9_sources.sh uses ssh to try to clone the openj9 and
omr repositories and that doesn't work out-of-the-box in a docker
container unless git has been configured to authenticate github.com
But https works just fine, so let's use https as the default. The
command line options can override with ssh-style repository names
if desired.
Signed-off-by: Mark Stoodley <mstoodle@ca.ibm.com>
=> Clone openj9 repositories using https by default

closed/autoconf/custom-hook.m4, closed/autoconf/generated-configure.sh
In some scenarios, for example when working with a shallow clone,
the git commands used to derive the latest SHA and build tag do
not work, resulting in uninvormative output from java -version.
This commit updates the git commands used to derive the SHA and
then to map to the build tag so that they work correctly even with
a shallow clone of the repository.
Fixes: #4
Signed-off-by: Mark Stoodley <mstoodle@ca.ibm.com>
=> Derive openjdk sha and tag more reliably

closed/autoconf/custom-hook.m4, closed/autoconf/generated-configure.sh, common/autoconf/generated-configure.sh
Revert the computation of the openj9-openjdk-jdk9 SHA.
Use '--abbrev=0' to get most recent tag on the current branch; otherwise we might find a tag on some other branch.
=> Fix discovery of SHA and recent tag

closed/OpenJ9.gmk
Openj9 requires mingw for compilation on windows
Set NO_USE_MINGW environment variable to use the default compiler (microsoft c compiler) instead
Fixes #50
Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>
=> Use default c compiler

closed/get_j9_source.sh, get_source.sh
I've seen a few automatic builds fail because the SHA of a PR merge commit becomes stale (happens if some unrelated PR is merged in the interim). The build should not continue (with the wrong code).
* improve bash version check
* more careful use of quotes
* simpler handling of defaults
* remove --revision option (mercurial)
* don't print usage when encountering the '--' option
=> Getting sources should stop on the first error

closed/OpenJ9.gmk
-m is equivalent to --touch and is supported on older versions of
the tar tool.  This is especially important for mac osx which
doesn't have gnu tar by default.
i.e.: on macosx the default tar supports:
```
-m    Don't restore modification times
```
while gnu tar supports
```
-m, --touch                don't extract file modified time
```
Using `-m` is more portable than `--touch`, even though the latter is clearer.
=> Use tar's '-m' rather than '--touch' to support older toolchains.

jdk/src/java.base/share/classes/jdk/internal/module/ModuleBootstrap.java
initializeSharedClassesSupport() should be called after all the modules
are loaded and defined.
Signed-off-by: Hang Shao <hangshao@ca.ibm.com>
=> Fix the SharedClasses Support

closed/OpenJ9.gmk, closed/autoconf/custom-hook.m4, closed/autoconf/generated-configure.sh, common/autoconf/generated-configure.sh, jdk/src/java.base/unix/conf/ppc64/jvm.cfg, make/common/Modules.gmk
Signed-off-by: Steve Groeger <groeges@uk.ibm.com>
Also requires an OMR change: https://github.com/eclipse/omr/pull/1802 in order to get AIX to build  100% successfully.
Fixes #62
=> Changes to build process to allow building of OpenJ9 on AIX

closed/OpenJ9.gmk, jdk/src/java.base/windows/conf/amd64/jvm.cfg
Fix the shared libraries staging directory for windows.
Update the windows configuration file with openj9 variants.
Issue: #18 
Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>
=> Update the jdk build for windows platforms

closed/autoconf/custom-hook.m4, closed/autoconf/generated-configure.sh, common/autoconf/generated-configure.sh
Works toward eclipse/openj9/36
Signed-off-by: Joe Dekoning <joe_dekoning@ca.ibm.com>
=> Add OSX support

closed/OpenJ9.gmk
Places various files into modules during the build to allow the
jdk and jre images to pick them up and get jlink to work.
Fixes issue #21
Signed-off-by: Jason Yong <yongja@uk.ibm.com>
=> Modifies closed/Open.gmk to put J9 files into java.base

closed/OpenJ9.gmk
Fix the stage_openj9_build_jdk generated target.
Stage shared libraries and redirector to:
- lib for *nix platforms 
- bin for windows platforms
Issues: #18 
Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>
=> Fix build breakage from #66

closed/OpenJ9.gmk
image library copy.
Signed-off-by: Andrew Leonard <andrew_m_leonard@uk.ibm.com>
=> Create $(OUTPUT_ROOT)/support/modules_libs/java.base directory before

closed/make/Main.gmk
Fix `Java 18.3` compile/build errors
Pass JCL_LEVEL=$(VERSION_MAJOR) to OpenJ9 makefile.
Closes: eclipse/openj9#293
Reviewer @pshipton 
FYI: @DanHeidinga @adamfarley 
Signed-off-by: Jason Feng <fengj@ca.ibm.com>
=> Fix Java 18.3 compile/build errors

closed/make/Main.gmk, make/Main.gmk
Remove obsolete J9JCL_GENSRC_MAKEFILE target
Remove j9vm-build duplicate prerequisite
Signed-off-by: Violeta Sebe <vsebe@ca.ibm.com>
=> Clean up openj9 build target dependencies

.gitignore
Remove trailing slash from /omr and /openj9 in the .gitignore file.
This means that they will be properly ignored when they are not real
folders, but symlinks. Old behaviour still works as expected.
Signed-off-by: Devin Nakamura <dnakamura@ca.ibm.com>
=> Modify omr and openj9 in .gitignore

jdk/make/launcher/Launcher-openj9.traceformat.gmk
Module com.ibm.traceformat renamed to openj9.traceformat in OpenJ9.
Changing filename and text of traceformat makefile to match the change.
Dependent on https://github.com/eclipse/openj9/pull/542
Tested `traceformat` executable locally with changes.
Signed-off-by: mikezhang <mike.h.zhang@ibm.com>
=> Change traceformat makefile to match module rename in OpenJ9

closed/OpenJ9.gmk
We will temporarily generate both version files in tr.source and 
compiler directories to avoid build breaks. A subsequent change will 
remove the tr.source file generation once the dependent builds pickup
this change.
Signed-off-by: Filip Jeremic <fjeremic@ca.ibm.com>
=> Rename runtimes/tr.source to runtimes/compiler

make/Images.gmk
Backporting of fix from OpenJDK10 onto JDK9 Extensions
http://hg.openjdk.java.net/jdk10/master/rev/7a7bc84f4b6c
Signed-off-by: Steve Groeger <GROEGES@uk.ibm.com>
=> Apply OpenJDK10 change to get AIX JRE image to be built

jdk/make/launcher/Launcher-openj9.dtfjview.gmk
Depends on https://github.com/eclipse/openj9/pull/703
Signed-off-by: mikezhang <mike.h.zhang@ibm.com>
=> Rename dtfjview makefile to match module rename in OpenJ9

closed/OpenJ9.gmk
As part of #86 we are temporarily generating tr.source/jit.version
and compiler/jit.version. Now that dependent changes have propagated
we can finally deprecate tr.source/jit.version.
Signed-off-by: Filip Jeremic <fjeremic@ca.ibm.com>
=> Deprecate generation of tr.source/jit.version

closed/autoconf/custom-hook.m4, closed/autoconf/generated-configure.sh, common/autoconf/generated-configure.sh
To avoid selecting unintended tags use `--match "jdk-9*"` when searching for the git tag to be included in `-version` output.
=> OpenJDK tags must match pattern 'jdk-9*'

closed/autoconf/custom-hook.m4, closed/autoconf/generated-configure.sh, common/autoconf/generated-configure.sh
fix for #93. If tag for current revision is not available, take it last tag added in repo.
java -version output before fix
```
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-adhoc.jenkins.openjdk)
Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20180102_81 (JIT enabled, AOT enabled)
OpenJ9   - 2df6261
OMR      - 25bb9f4
OpenJDK  - f1a22d1 based on )
```
java -version output after fix 
```
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-adhoc.bhamaram.openjdk)
Eclipse OpenJ9 VM (build 2.9, JRE 9 Linux amd64-64 Compressed References 20180104_000000 (JIT enabled, AOT enabled)
OpenJ9   - 4cc5b0a
OMR      - 66568c6
OpenJDK  - f1a22d1 based on jdk-9+181)
```
=> fix OPENJDK_TAG in java version output

jdk/src/jdk.jlink/share/classes/jdk/tools/jlink/internal/plugins/GenerateJLIClassesPlugin.java, jdk/src/jdk.jlink/share/classes/module-info.java
We don't need them any more, as patches have been made to OpenJ9 to
compensate for their absence.
=> Undo JLink Module Extensions

closed/openj9_version_info.h.in
The vendor constants should be set by the vendor (user) at build 
time. Setting it internally only complicates things later, so we 
will remove these definitions here, and compensate in OpenJ9.
=> Remove constants that the user should set themselves

closed/make/common/Modules.gmk
Besides the 'clean' target, we can avoid this work for 'dist-clean', 'help' and all targets beginning with 'clean' (e.g. clean-java.base).
=> Avoid generating j9jcl sources for more targets

.gitignore
If the user turns their local clone into a git project, this
ignore prevents them accidentally committing their project file
into the git repository.
=> Exclude optional eclipse project file

jdk/make/gensrc/GensrcMisc.gmk, jdk/src/java.base/share/classes/java/lang/VersionProps.java.template
Extensions used to add the OpenJDK SHA to the java -version
output.
Now OpenJ9 does it in eclipse/openj9#1010, so this code isn't needed anymore.
=> Remove OpenJDK SHA add-on code for extensions

jdk/make/gensrc/GensrcMisc.gmk
Remove a space which was the only difference relative to OpenJDK.
=> Undo all changes for OpenJ9

closed/OpenJ9.gmk, closed/openj9_version_info.h.in
Remove JVM version 2.9
Added a vendor specific define
`java.vm.version = OPENJ9_TAG` or `OPENJ9_BRANCH-OPENJ9_SHA` when there is no tag.
Moved generated `openj9_version_info.h` from `util` to `include`
Related PRs:
https://github.com/eclipse/openj9/pull/1095
https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/36
Reviewer @DanHeidinga 
FYI @pshipton 
Signed-off-by: Jason Feng <fengj@ca.ibm.com>
=> Remove JVM version 2.9

closed/OpenJ9.gmk
Note that NO_USE_MINGW is tested using ifdef, so ensure the flag is not
defined at all.
Depends on eclipse/openj9#1099
Signed-off-by: Peter Bain <peter_bain@ca.ibm.com>
=> Enable mingw compiler on Windows Java 9

closed/OpenJ9.gmk
Find `OpenJ9` tag associated with current commit
Find `OpenJ9` tag associated with current commit specified by `OPENJ9_SHA` and remove `stderr` output in case there is no such `tag` found.
Tested the script manually in a personal repo.
Closes: eclipse/openj9#1140
Related to PR: https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/40
Reviewer @Peter-Shipton 
FYI: @daniel-heidinga 
Signed-off-by: Jason Feng <fengj@ca.ibm.com>
=> Find OpenJ9 tag associated with current commit

closed/OpenJ9.gmk, closed/autoconf/custom-hook.m4, closed/autoconf/custom-spec.gmk.in, closed/autoconf/generated-configure.sh, closed/make/Main.gmk, common/autoconf/generated-configure.sh
With all the review changes the previous PR became obsolete. This PR now covers all the changes required (in this project) for a working 32 bit cross compile hosted on x86 and targeting armhf.
=> Support composing 32 bit builds for arm

jdk/make/src/classes/build/tools/module/GenModuleInfoSource.java
This extension allows the user to use "requires" lines in
their module-info.java.extra files. This functionality is
only required because the OpenJ9 VM needed to add a
"requires" that is unique to that VM. Now it doesn't need
it anymore, we can remove this extension.
=> Remove GenModuleInfoSource Extension

closed/get_j9_source.sh
Checkout `branch/sha` to keep `branch` info
Closes: https://github.com/eclipse/openj9/issues/1149
Reviewer @Peter-Shipton 
FYI: @daniel-heidinga 
Signed-off-by: Jason Feng <fengj@ca.ibm.com>
=> Checkout branch/sha to keep branch info

jdk/src/java.base/share/classes/java/nio/Bits.java
There are no extensions in this file, and therefore an IBM copyright
notice is superfluous. Removing.
=> Remove superfluous copyright

closed/src/java.rmi/share/classes/module-info.java.extra, jdk/src/java.rmi/share/classes/module-info.java
Open extensions have to be merged with a copy of OpenJDK,
which is undesirable because it leads to merge conflicts
and release delays. Closed extensions don't have this
problem, so I'm putting this extension into closed.
=> Move Shared classes module info extension into closed

closed/src/java.rmi/share/classes/module-info.java.extra
The big comment in this file was taken from the wrong
source by accident. This corrects the error.
=> Correct flawed comment in module info file

jdk/src/java.base/share/classes/jdk/internal/misc/Unsafe.java
OpenJ9 overwrites this file now, so the extensions are no longer
required to make this file compatible with OpenJ9.
=> Undo DBB extensions to Unsafe.java

closed/OpenJ9.gmk
Adjust missing/redundant uses of `$(notdir)`.
Issue: #132
Signed-off-by: Keith W. Campbell <keithc@ca.ibm.com>
=> Correct placement of shared libraries

closed/OpenJ9.gmk
The function DependOnVariable seems to have trouble with
empty variables (like `OPENJ9_TAG` will often be). Instead
we build an auxilliary variable which will never be empty
and depend upon its value.
Signed-off-by: Keith W. Campbell <keithc@ca.ibm.com>
=> Rework rule to keep openj9_version_info.h up-to-date

closed/OpenJ9.gmk
SIDECAR19-SE-B175 is replaced by SIDECAR19-SE-OPENJ9.
Depends on eclipse/openj9#1178
Signed-off-by: Peter Shipton <Peter_Shipton@ca.ibm.com>
=> Removed an obsolete OpenJ9 jcl preprocessor configuration

closed/OpenJ9.gmk, closed/autoconf/custom-hook.m4, closed/autoconf/custom-spec.gmk.in, closed/autoconf/generated-configure.sh, closed/make/DDR-gensrc.gmk, closed/make/DDR-jar.gmk, closed/make/Main.gmk, common/autoconf/generated-configure.sh
* add configure option '--enable-ddr' (enabled by default for xa64)
* enable opt_useOmrDdr accordingly
* build j9ddr.jar for inclusion in openj9.dtfj.jmod
Depends on eclipse/openj9#1399.
=> Enable DDR support for Linux x86-64

closed/make/common/Modules.gmk
Build and run the preprocessor only when Main.gmk is invoked with the goal 'create-main-targets-include' and not every time Modules.gmk is read by make.
This avoids scores of evaluations of the build-openj9-tools and generate-j9jcl-sources targets in OpenJ9.gmk which improved build times significantly.
=> Refine the trigger for generation of J9JCL sources

jdk/src/jdk.jdwp.agent/share/native/libjdwp/debugInit.c, jdk/src/jdk.jdwp.agent/share/native/libjdwp/debugInit.h, jdk/src/jdk.jdwp.agent/share/native/libjdwp/debugLoop.c, jdk/src/jdk.jdwp.agent/share/native/libjdwp/eventHelper.c
Normally, the event helper thread suspends all threads, then the debug loop in
the listener thread receives a command to resume.  The debugger may deadlock if
the debug loop in the listener thread starts processing commands (e.g. resume
threads) before the event helper completes the initialization (and suspends
threads).
This patch adds synchronization to ensure the event helper completes the
initialization sequence before debugger commands are processed.
@andrew-m-leonard FYI.
Signed-off-by: Peter Bain <peter_bain@ca.ibm.com>
=> Fix race condition in jdwp
